services:

  db:
    image: mysql:latest
    container_name: db_test_version4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: DevOpsV4
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3340:3306"
    volumes:
      - mysql_data4:/var/lib/mysql
      - ./DevOpsV4.sql:/docker-entrypoint-initdb.d/DevOpsV4.sql
    networks:
      - mysql_phpmyadmin4
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_test_version4
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8040:80"
    networks:
      - mysql_phpmyadmin4

  backend:
    build: ./Back-End
    image: devopsv4-backend:latest
    restart: always
    container_name: backend_version4
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
      TOKEN_KEY: PHATCHAA
      DB_HOST: db
      DB_NAME: DevOpsV4
      DB_USER: user
      DB_PASSWORD: 1234
      DB_PORT: 3306
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mysql_phpmyadmin4
  
  frontend:
    build: ./Font-End
    image: devopsv4-frontend:latest
    restart: always
    container_name: frontend_version4
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mysql_phpmyadmin4

networks:
  mysql_phpmyadmin4:
    driver: bridge

volumes:
  mysql_data4:
  backend_uploads:

