services:
  db:
    image: mysql:latest
    container_name: db_test_version4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: DevOpsV4
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3340:3306"
    volumes:
      - mysql_data4:/var/lib/mysql
    networks:
      - mysql_phpmyadmin4
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_test_version4
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8040:80"
    networks:
      - mysql_phpmyadmin4

networks:
  mysql_phpmyadmin4:
volumes:
  mysql_data4:
